version: "3"
services:
  minecraft:
    image: itzg/minecraft
    environment:
      - EULA=true
    networks:
      - traefik
    volumes:
      - ${MINECRAFT_DATA_PATH}:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.tcp.routers.minecraft.rule=Host(`${MINECRAFT_DOMAIN}`)
        - traefik.tcp.routers.minecraft.entryPoints=minecraft
        - traefik.tcp.services.minecraft.loadbalancer.server.port=25565

networks:
  traefik:
    external: true
